### ISSUE TITLE
How to use the SDK / flash the image to the device?

### ISSUE THREAD

**Issue by rustyx** [DeanCording/nRF24LE1_SDK#6]
Is there any documentation available on how to use this SDK and most importantly upload the image to the device without resorting to commercial tools?

**Comment by DeanCording** [comment]
There is no documentation for the SDK but it is a straight forward implementation of the lower level product specification for the nRF24LE1 which can be downloaded from https://infocenter.nordicsemi.com/pdf/nRF24LE1_PS_v1.6.pdf


Have a look at https://github.com/DeanCording/nRF24LE1_Programmer for using an Arduino as a programmer for the nRF24LE1
