### ISSUE TITLE
RF_W_ACK_PAYLOAD has wrong value

### ISSUE THREAD

**Issue by archfurry** [DeanCording/nRF24LE1_SDK#8]
According to [NRF24LE1 specs](https://infocenter.nordicsemi.com/pdf/nRF24LE1_PS_v1.6.pdf) the value for SPI command RF_W_ACK_PAYLOAD should be 0xA8 (0b1010_1PPP, where PPP is a pipe number from 0 to 5)
Current value for RF_W_ACK_PAYLOAD in `rf.h` is 0xA1 (0b1010_0001), which is wrong.

**Comment by DeanCording** [comment]
Fix merged
